export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A giant octopus playing a grand piano in a Victorian-era concert hall",
  "A dragon made of flowing water coiled around a lighthouse during a storm",
  "An abstract painting of a forest where the trees are made of vibrant colored glass",
  "A steampunk-inspired hot air balloon race over a city made of clockwork",
  "A neon-lit cyberpunk street market in the rain",
  "A whimsical house made entirely of candy and sweets in the middle of a forest",
  "A futuristic city floating in the clouds with waterfalls cascading down the sides",
  "A phoenix rising from the ashes in a barren desert landscape",
  "A medieval knight made of flowers standing in a field of blooming wildflowers",
  "A surreal underwater scene with jellyfish that glow like neon lights",
  "A spaceship shaped like a giant seashell flying through space",
  "A whimsical carousel with fantastical creatures instead of horses",
  "A Victorian-era laboratory filled with strange, glowing potions and inventions",
  "A cozy cottage in the woods with a roof made of giant leaves",
  "A futuristic metropolis at night with towering skyscrapers covered in greenery",
  "A surreal landscape where the mountains are made of crystal and the rivers flow with light",
  "A dreamlike scene of a floating island with a single tree and a small house",
  "A giant whale swimming through the clouds in a colorful sunset sky",
  "A mystical library where the books float in the air and glow with a soft light",
  "A cybernetic tiger prowling through a neon jungle",
  "A serene garden with trees that have leaves made of stained glass",
  "A surreal landscape with giant mushrooms that glow in the dark",
  "A whimsical bakery where the cakes and pastries are alive and dance on the counters",
  "A floating city made of bubbles drifting above the ocean",
  "A futuristic train speeding through a tunnel of light in a neon-lit city",
  "A peaceful forest where the trees are made of twisted metal and glass",
  "A dragonfly with wings made of circuit boards flying over a digital landscape",
  "A magical blacksmith's forge where the tools and weapons are alive",
  "A snowy mountain peak with a glowing crystal at its summit",
  "A serene lake with water that reflects the night sky full of stars",
  "A futuristic city built inside a giant tree with glowing roots",
  "A fantastical creature that is half-lion, half-peacock standing in a lush jungle",
  "A mystical cave where the walls are covered in glowing runes and crystals",
  "A steampunk airship docked at a floating city in the clouds",
  "A tranquil beach with sand that sparkles like diamonds",
  "A futuristic robot garden with plants made of metal and glass",
  "A magical forest where the trees have faces and the animals can talk",
  "A celestial palace floating among the stars with a galaxy swirling around it",
  "A mysterious portal in the middle of a dense forest with glowing symbols",
  "A giant treehouse village connected by rope bridges high above the ground",
  "A serene underwater temple illuminated by bioluminescent creatures",
  "A futuristic spacecraft shaped like a giant lotus flower",
  "A peaceful meadow with wildflowers that glow softly in the dark",
  "A mystical mountain range with peaks that touch the clouds and glow with a golden light",
  "A steampunk-inspired city with gears and cogs visible in the buildings and streets",
  "A tranquil forest clearing with a crystal-clear pond reflecting the moonlight",
  "A surreal landscape where the sky is filled with floating islands and waterfalls",
  "A futuristic laboratory with robots working on strange and glowing inventions",
  "A floating castle made of crystal and light hovering above a calm ocean",
];
